import React, { useState } from 'react';
import {
  Container,
  Box,
  Heading,
  Text,
  Stack,
  Card,
  CardBody,
  useColorModeValue,
  Flex,
  Collapse,
  Button,
  Icon,
  Badge,
  Link
} from '@chakra-ui/react';
import { FiChevronDown, FiChevronUp, FiHelpCircle, FiAward, FiTrendingUp, FiUsers, FiSettings } from 'react-icons/fi';

const FAQs = () => {
  const cardBg = useColorModeValue('white', 'gray.700');
  const [expandedFAQs, setExpandedFAQs] = useState({});

  const toggleFAQ = (faqId) => {
    setExpandedFAQs(prev => ({
      ...prev,
      [faqId]: !prev[faqId]
    }));
  };

  const faqCategories = [
    {
      title: 'Getting Started',
      icon: FiHelpCircle,
      color: 'blue',
      faqs: [
        {
          id: 'getting-started-1',
          question: 'What is the Level-Up Programme?',
          answer: 'The Level-Up Programme is a structured program designed to help you grow as a Deriv partner by completing milestones in the Level-Up Journey. You earn tokens by bringing clients, recruiting sub-affiliates, making them trade, and earning commissions, which unlock rewards to gain prizes. It provides training, support, and incentives to maximize your success.'
        },
        {
          id: 'getting-started-2',
          question: 'How long does it take to complete the program?',
          answer: 'The timeline varies based on your dedication and business development pace. The BASIC level can be completed in a few days, while advancing through MEDIUM, HIGH, and PRO levels depends on your success in bringing clients and empowering them to trade. Most active partners see significant progress within 2-3 months.'
        },
        {
          id: 'getting-started-3',
          question: 'How do I start my partner journey?',
          answer: 'Welcome to the Partner Activation Academy! Start by completing your Level-Up Journey. Begin with the BASIC Level actions like completing KYC and setting up your payment method. These foundational steps will prepare you for earning tokens and advancing through the program.'
        },
        {
          id: 'getting-started-4',
          question: 'Can I skip levels or complete actions out of order?',
          answer: 'Some actions are mandatory (like completing KYC and setting up your payment method), but many other actions can be completed in any order. However, to unlock each reward level, you need to meet the specific token milestones required.'
        }
      ]
    },
    {
      title: 'Actions and Tokens',
      icon: FiTrendingUp,
      color: 'green',
      faqs: [
        {
          id: 'actions-tokens-1',
          question: 'What is KYC?',
          answer: 'KYC stands for "Know Your Customer." In Deriv, KYC refers to the process where clients and partners are required to verify their identity and home address by submitting specific documents (such as ID, passport, bills, etc.). This is done to ensure compliance with regulations and to protect against fraud.'
        },
        {
          id: 'actions-tokens-2',
          question: 'What is a payment method?',
          answer: 'A payment method in Deriv is the way clients can deposit or withdraw funds from their trading accounts. Examples of payment methods include credit/debit cards, e-wallets, bank transfers, and cryptocurrencies.'
        },
        {
          id: 'actions-tokens-3',
          question: 'What is a Client?',
          answer: 'A client in Deriv is any individual or entity who creates an account and uses the platform\'s services to trade financial instruments.'
        },
        {
          id: 'actions-tokens-4',
          question: 'How do I bring my first clients or sub-affiliates?',
          answer: 'Below each action, you\'ll see a variety of courses, e-books, PDFs, YouTube videos, and more educational materials to cover strategies for client acquisition, including identifying your target audience, creating compelling content, and leveraging your network. Focus on building trust and providing value to potential clients or sub-affiliates.'
        },
        {
          id: 'actions-tokens-5',
          question: 'What is an affiliate/partner?',
          answer: 'An affiliate in Deriv is a person or organization that promotes Deriv\'s services in exchange for commissions. Affiliates refer clients to Deriv through special links or codes and earn rewards when those clients open accounts and start trading.'
        },
        {
          id: 'actions-tokens-6',
          question: 'What is a sub-affiliate?',
          answer: 'A sub-affiliate in Deriv is someone who is recruited by an affiliate to join the affiliate program. The main affiliate earns a percentage of the commissions generated by their sub-affiliates.'
        },
        {
          id: 'actions-tokens-7',
          question: 'What is the trading volume in Deriv?',
          answer: 'Trading volume in Deriv refers to the total value or size of all trades executed by a client or by clients referred by an affiliate over a specific period.'
        },
        {
          id: 'actions-tokens-8',
          question: 'What are commissions in Deriv?',
          answer: (
            <span>
              Commissions are the earnings paid to affiliates based on the trading volume or activity generated by the clients they refer. This is a way for Deriv to reward partners for bringing in more clients or transactions. The exact calculation depends on the specific products and client activity levels. Detailed commission structures are available here: {' '}
              <Link href="https://docs.deriv.com/partners/ib-cfds-commissions-how-its-calculated.pdf" color="blue.500" isExternal>
                https://docs.deriv.com/partners/ib-cfds-commissions-how-its-calculated.pdf
              </Link>
            </span>
          )
        },
        {
          id: 'actions-tokens-9',
          question: 'How do I earn tokens?',
          answer: 'Affiliates earn tokens by completing specific actions. These tokens can later be redeemed for rewards such as gift cards, courses, premium tools, mentorships and more. The system is designed to promote incremental progress, turning small achievements into real motivation.'
        },
        {
          id: 'actions-tokens-10',
          question: 'What are the token milestones?',
          answer: 'There are key token milestones that unlock new opportunities and recognition within the partner program. Your progress is tracked on your dashboard and throughout the platform. The more tokens you earn, the higher your ranking and rewards potential.'
        },
        {
          id: 'actions-tokens-11',
          question: 'Can they hold on to their earned tokens, which are already eligible for a lower reward, and wait until they reach a higher or intermediate reward instead?',
          answer: 'Yes, they can redeem the reward at the stage they want ($30, $50, $70 or $100).'
        },
        {
          id: 'actions-tokens-12',
          question: 'Example: If the action is to bring 5 clients and it\'s worth 500 tokens, and I bring 10 clients, do the tokens double?',
          answer: 'No, if your result exceeds the target of the action, it doesn\'t affect the number of tokens you earn. For example, in this case, even if you bring 10 clients, the action will still be worth 500 tokens. The only time the token value changes is in the "Pro" stage, where there are "same kind of actions" but more challenging, which are worth more tokens, but only in that specific stage.'
        },
        {
          id: 'actions-tokens-13',
          question: 'Can tokens be transferred to another partner or account?',
          answer: 'No, tokens are personal and non-transferable. They are strictly tied to your partner account.'
        },
        {
          id: 'actions-tokens-14',
          question: 'Are there any actions that can be completed more than once for extra tokens?',
          answer: 'No, each action in the Level-Up Program can only be completed once per partner account.'
        },
        {
          id: 'actions-tokens-15',
          question: 'Can I complete the actions in any order, or do I need to follow a sequence?',
          answer: 'Apart from the "basic" actions, which are mandatory to unlock any rewards, the remaining actions can be completed in any order, giving you flexibility as you progress.'
        }
      ]
    },
    {
      title: 'Rewards',
      icon: FiAward,
      color: 'purple',
      faqs: [
        {
          id: 'rewards-1',
          question: 'How do I redeem rewards?',
          answer: 'Once you\'ve accumulated enough tokens, you can redeem them for various rewards including Amazon gift cards, Spotify Premium, Canva Pro, Netflix subscriptions, and more. Contact your partner manager to process your reward redemption. We recommend saving up for higher-value tiers to maximize your rewards.'
        },
        {
          id: 'rewards-2',
          question: 'What reward tiers are available?',
          answer: 'We offer four reward tiers: $30, $50, $70, and $100 in prizes. Each tier includes various options like gift cards, software subscriptions, course vouchers, and coaching sessions. Higher tiers offer better value and more premium rewards.'
        },
        {
          id: 'rewards-3',
          question: 'If they received the reward at for example the second stage ($50), can they continue earning rewards?',
          answer: 'No, they can do it just once. Then, they start the "normal" Tiering program journey.'
        },
        {
          id: 'rewards-4',
          question: 'Are there any geographic restrictions for certain digital rewards (gift cards, subscriptions, etc.)?',
          answer: 'All of them are digital rewards and selected to be redeemable globally. However, some gift cards or services may have regional restrictions. Check them before redeeming them.'
        },
        {
          id: 'rewards-5',
          question: 'If I have trouble redeeming a digital reward (e.g., a gift card code doesn\'t work), what should I do?',
          answer: 'Please contact support or your country manager immediately with details of the issue. We\'ll work to resolve it and ensure you receive a valid reward or a replacement option.'
        },
        {
          id: 'rewards-6',
          question: 'Can I choose more than one reward if I have enough tokens for multiple tiers?',
          answer: 'No, each partner can only redeem one reward during the Level-Up Program.'
        }
      ]
    },
    {
      title: 'Technical & Account',
      icon: FiSettings,
      color: 'red',
      faqs: [
        {
          id: 'technical-1',
          question: 'I\'m having trouble with KYC verification. What should I do?',
          answer: 'Ensure all your documents are clear, valid, and match the information in your account. Common issues include blurry photos, expired documents, or mismatched names. If you continue having problems, contact our support team with your specific error messages for personalized assistance.'
        },
        {
          id: 'technical-2',
          question: 'How do I set up my payment method?',
          answer: 'Go to your account settings and navigate to the payment methods section. You can add bank accounts, e-wallets, or other supported payment options. Ensure your payment method matches your verified identity for smooth commission payouts.'
        },
        {
          id: 'technical-3',
          question: 'How do I track my clients?',
          answer: 'You can track your clients through your partner dashboard, which provides real-time updates on client activity, registrations, and trading performance.'
        },
        {
          id: 'technical-4',
          question: 'Can I track my progress in real-time?',
          answer: 'Yes! Your dashboard provides real-time updates on your tokens, completed actions, leaderboard ranking, and overall progress. The progress bar shows your current position and next milestones. All your achievements and statistics are updated automatically.'
        },
        {
          id: 'technical-5',
          question: 'Who do I contact for additional support?',
          answer: 'For general questions, start with these FAQs. For account-specific issues, contact your assigned partner manager. For technical problems, reach out to our support team through the help desk. For reward redemptions, coordinate with your country manager.'
        },
        {
          id: 'technical-6',
          question: 'What security measures are in place for my data during KYC and payments?',
          answer: 'Deriv uses industry-standard encryption and strict data protection protocols during the KYC process and when handling payment methods. Your documents and information are securely stored and are never shared with third parties outside what is required by our regulators.'
        },
        {
          id: 'technical-7',
          question: 'What if I lose access to my account or email before receiving my reward?',
          answer: 'Please contact support immediately for help recovering your account. Account and reward eligibility are based on the successful completion of Identity Verification.'
        },
        {
          id: 'technical-8',
          question: 'Can I access the Level-Up dashboard from mobile devices?',
          answer: 'Yes! You can access your Level-Up dashboard from any browser, including on tablets or smartphones.'
        },
        {
          id: 'technical-9',
          question: 'Is my progress saved if I temporarily stop participating?',
          answer: 'Yes. Your completed actions, earned tokens, and progress are safely saved. You can resume your Level-Up journey at any time.'
        }
      ]
    }
  ];

  return (
    <Container maxW="container.xl" py={5}>
      <Stack spacing={8}>
        {/* Header */}
        <Box>
          <Heading mb={2}>Frequently Asked Questions</Heading>
          <Text color="gray.600">
            Find answers to common questions about the Partner Activation Academy.
          </Text>
        </Box>

        {/* FAQ Categories */}
        <Stack spacing={6}>
          {faqCategories.map((category) => (
            <Box key={category.title}>
              <Flex align="center" mb={4}>
                <Icon as={category.icon} boxSize={6} color={`${category.color}.500`} mr={3} />
                <Heading size="lg">{category.title}</Heading>
                <Badge ml={3} colorScheme={category.color}>{category.faqs.length} questions</Badge>
              </Flex>
              
              <Stack spacing={3}>
                {category.faqs.map((faq) => (
                  <Card 
                    key={faq.id}
                    bg={cardBg} 
                    boxShadow="md" 
                    borderRadius="lg"
                    borderWidth="1px"
                    borderColor={`${category.color}.200`}
                  >
                    <CardBody>
                      <Stack spacing={3}>
                        {/* Question - Always Visible */}
                        <Button
                          variant="ghost"
                          onClick={() => toggleFAQ(faq.id)}
                          justifyContent="space-between"
                          size="lg"
                          p={0}
                          h="auto"
                          _hover={{ bg: 'transparent' }}
                        >
                          <Flex align="center" justify="space-between" w="full">
                            <Text fontSize="md" fontWeight="semibold" textAlign="left">
                              {faq.question}
                            </Text>
                            <Icon 
                              as={expandedFAQs[faq.id] ? FiChevronUp : FiChevronDown} 
                              boxSize={5}
                              color="gray.500"
                              ml={4}
                            />
                          </Flex>
                        </Button>

                        {/* Answer - Collapsible */}
                        <Collapse in={expandedFAQs[faq.id]} animateOpacity>
                          <Box pt={2} borderTop="1px" borderColor="gray.200">
                            <Text color="gray.600" lineHeight="1.6">
                              {faq.answer}
                            </Text>
                          </Box>
                        </Collapse>
                      </Stack>
                    </CardBody>
                  </Card>
                ))}
              </Stack>
            </Box>
          ))}
        </Stack>

        {/* Contact Support */}
        <Card bg={cardBg} boxShadow="lg" borderRadius="lg" borderWidth="2px" borderColor="blue.200">
          <CardBody>
            <Stack spacing={4}>
              <Heading size="md" color="blue.600">Still Need Help?</Heading>
              <Text color="gray.600">
                Can't find the answer you're looking for? Our support team is here to help you succeed in your partner journey.
              </Text>
              <Flex gap={4} flexWrap="wrap">
                <Button colorScheme="blue" variant="solid">
                  Contact Partner Manager
                </Button>
                <Button colorScheme="blue" variant="outline">
                  Submit Support Ticket
                </Button>
              </Flex>
            </Stack>
          </CardBody>
        </Card>
      </Stack>
    </Container>
  );
};

export default FAQs; 